### ISSUE TITLE
What pins do you use??

### ISSUE THREAD

**Issue by brakthehun** [MLXXXp/ArduboyTones#1]
I couldn't find any documentation on which pin to use. What pin do I use for low volume and what pair for high volume??

**Comment by MLXXXp** [comment]
In this library, the pins are hard coded specifically for the [Arduboy](https://arduboy.com/). The piezo speaker is wired between Arduino pins 5 (PC6) and 13 (PC7) for an ATmega32U4 processor. The speaker is wired between two pins, instead of between one pin and ground, to allow two different volumes to be produced.

The pins used are defined in the [ArduboyTones.h](https://github.com/MLXXXp/ArduboyTones/blob/972fe8117002da47073b6c1835117d654a03e16f/src/ArduboyTones.h#L123) file. By changing these defines, different pins can be used.
